export const allSkills = [
	// --- Soft Skills (Shaxsiy va ijtimoiy) ---
	"Moslashuvchanlik (adaptivlik)",
	"Tashabbuskorlik",
	"Ishbilarmonlik etikasi",
	"Insonlar bilan ishlash",
	"Tanqidiy fikrlash",
	"Emotional barqarorlik",
	"Proaktivlik",
	"Vaqtni boshqarish (Time management)",
	"Konfliktlarni boshqarish",
	"Muzokara olib borish",
	"Notiqlik san'ati",
	"Liderlik",
	"Jamoada ishlash",
	"Stressga chidamlilik",
	"Muammolarni kreativ hal qilish",
	"Qaror qabul qilish",
	"Strategik fikrlash",
	"Faol tinglash",
	"Empatiya",
	"Delegatsiya qilish",
	"Feedback berish va qabul qilish",
	"O'z-o'zini motivatsiya qilish",
	"Intizom",
	"Mas'uliyatlilik",
	"Taqdimot ko'nikmalari",
	"Networking",
	"Kross-madaniy muloqot",

	// --- IT & Dasturlash (Hard Skills) ---
	"GraphQL",
	"REST API",
	"gRPC",
	"JavaScript",
	"TypeScript",
	"React.js",
	"Vue.js",
	"Angular",
	"Node.js",
	"Python",
	"Java",
	"C#",
	"C++",
	"Go (Golang)",
	"PHP",
	"Laravel",
	"Django",
	"FastAPI",
	"Spring Boot",
	"Ruby on Rails",
	"Flutter",
	"React Native",
	"Swift",
	"Kotlin",
	"SQL",
	"NoSQL",
	"PostgreSQL",
	"MongoDB",
	"Redis",
	"Elasticsearch",
	"Docker",
	"Kubernetes",
	"CI/CD",
	"AWS",
	"Azure",
	"Google Cloud Platform",
	"Firebase",
	"Git",
	"GitHub",
	"GitLab",
	"Microservices",
	"Serverless",
	"Unit Testing",
	"Integration Testing",
	"Redux",
	"Zustand",
	"Tailwind CSS",
	"Bootstrap",
	"SASS/SCSS",
	"Next.js",
	"Nuxt.js",
	"WebSockets",
	"OAuth 2.0",
	"Web Security",
	"Terraform",
	"Ansible",

	// --- Sun'iy Intellekt va Data ---
	"Machine Learning",
	"Deep Learning",
	"Data Analysis",
	"Data Science",
	"Pandas",
	"NumPy",
	"TensorFlow",
	"PyTorch",
	"Prompt Engineering",
	"NLP (Natural Language Processing)",
	"Computer Vision",
	"Big Data",
	"Hadoop",
	"Spark",
	"Power BI",
	"Tableau",
	"Data Visualization",
	"Scikit-learn",

	// --- Biznes, Menejment va HR ---
	"HRMS tizimlari",
	"CRM tizimlari",
	"Project Management",
	"Agile",
	"Scrum",
	"Kanban",
	"Lean",
	"Product Management",
	"Business Analysis",
	"Bozorni tahlil qilish",
	"Risk menejmenti",
	"KPI boshqaruvi",
	"OKR tizimi",
	"Talent Acquisition",
	"Onboarding",
	"Employer Branding",
	"Sotuv texnikalari",
	"B2B Sales",
	"B2C Sales",
	"Mijozlar bilan aloqa (Customer Success)",
	"Cold Calling",
	"Savdo voronkasi (Sales Funnel)",

	// --- Marketing va Dizayn ---
	"SEO (Search Engine Optimization)",
	"SMM (Social Media Marketing)",
	"Google Ads",
	"Targeting",
	"Content Marketing",
	"Email Marketing",
	"Copywriting",
	"Storytelling",
	"Influencer Marketing",
	"Affiliate Marketing",
	"UI/UX Design",
	"Figma",
	"Adobe Photoshop",
	"Adobe Illustrator",
	"Adobe Premiere Pro",
	"After Effects",
	"Motion Design",
	"3D Modeling",
	"Blender",
	"Canva",

	// --- Moliya va Ma'muriyat ---
	"Moliyaviy tahlil",
	"Buxgalteriya",
	"Soliq hisobi",
	"Audit",
	"P&L hisoboti",
	"Budjetlashtirish",
	"Excel (Advanced)",
	"Google Sheets",
	"1C: Buxgalteriya",
	"Huquqiy savodxonlik",
	"Shartnomalar bilan ishlash",
	"Logistika",
	"Supply Chain Management",
	"Xaridlar boshqaruvi",
	"E-commerce",

	// --- Qo'shimcha va Umumiy ---
	"Ingliz tili (B2/C1/C2)",
	"Rus tili",
	"Nemis tili",
	"Xitoy tili",
	"Turk tili",
	"Tezkor yozish",
	"Ma'lumotlarni qidirish (OSINT)",
	"Kiberxavfsizlik",
	"Pentesting",
	"QA Manual",
	"QA Automation",
	"Technical Writing",
	"Loyiha hujjatlarini yuritish",
	"Public Relations (PR)",
	"Event Management",
	"Sifat nazorati (Quality Control)",
	"Ishlab chiqarishni boshqarish",
	"ERP tizimlari",
	"SAP",
	"Oracle",
	"Asana",
	"Trello",
	"Jira",
	"Notion",
	"Slack",
	"Microsoft Teams",
	"Zoom/Google Meet",
	"Vaqt hisobini yuritish",
	"Hujjat aylanishi (EDO)",
	"Arxiv ishi",
	"Eksport-import operatsiyalari",
	"Franchising",
	"Startapni kengaytirish (Scaling)",
	"Investorlar bilan ishlash",
	"Pitch Deck tayyorlash",
	"Ijtimoiy psixologiya",
	"Neyromarketing",
	"Sotsiologik tadqiqotlar",
	"Sizdagi yashirin qobiliyatlar",
	"Ekologik mas'uliyat (ESG)",
	"O'zaro hamkorlik (Partnerships)",
	"Loyiha budjetini optimallashtirish",
	"Kreativ yozish",
	"Podcast yuritish",
	"Video Production",
	"Sound Design",
	"Game Development",
	"Unity",
	"Unreal Engine",
	"Blockchain",
	"Web3",
	"Smart Contracts",
	"Solidity",
	"Cyberspace Law",
];
